services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file: local.env  
    ports: 
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    env_file: local.env
    depends_on:
      - db
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: True
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    restart: always
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: